#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
# Sample command: docker build --build-arg VCS_REF=`git rev-parse — short HEAD` --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` -t $IMAGE_NAME .

docker build --build-arg COMMIT_ID=`git rev-parse --short HEAD` -t $IMAGE_NAME .